// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_rvZYbl9oUw3HvAE2RYJmnq7IWiG5hhw',
    appId: '1:516306315147:web:80d9b5cdaa88533942318e',
    messagingSenderId: '516306315147',
    projectId: 'ai-note-scanner',
    authDomain: 'ai-note-scanner.firebaseapp.com',
    storageBucket: 'ai-note-scanner.firebasestorage.app',
    measurementId: 'G-KHY5HJ696S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTfabo3gTOls7wsGHVjySKtUDUwTo40yE',
    appId: '1:516306315147:android:83907bfccab36e1442318e',
    messagingSenderId: '516306315147',
    projectId: 'ai-note-scanner',
    storageBucket: 'ai-note-scanner.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbpODmyacHt9OCNEGzZU76acg0Y-T4tYQ',
    appId: '1:516306315147:ios:271013ffab422be342318e',
    messagingSenderId: '516306315147',
    projectId: 'ai-note-scanner',
    storageBucket: 'ai-note-scanner.firebasestorage.app',
    iosBundleId: 'com.example.aiNoteScanner',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbpODmyacHt9OCNEGzZU76acg0Y-T4tYQ',
    appId: '1:516306315147:ios:271013ffab422be342318e',
    messagingSenderId: '516306315147',
    projectId: 'ai-note-scanner',
    storageBucket: 'ai-note-scanner.firebasestorage.app',
    iosBundleId: 'com.example.aiNoteScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_rvZYbl9oUw3HvAE2RYJmnq7IWiG5hhw',
    appId: '1:516306315147:web:eda6a925809ce76b42318e',
    messagingSenderId: '516306315147',
    projectId: 'ai-note-scanner',
    authDomain: 'ai-note-scanner.firebaseapp.com',
    storageBucket: 'ai-note-scanner.firebasestorage.app',
    measurementId: 'G-2KXJ5NSZGV',
  );
}
